### ISSUE TITLE
Add a zip file of the gh-pages (static web app) as a release, to easily download it for offline use

### ISSUE THREAD

**Issue by Naereen** [felixhao28/JSCPP#148]
Hi again,
I just tried to download a zip file from GitHub, when viewing the `gh-pages`, and oh yes opening the index.html works on my laptop even offline.
It's great, but not advertised per se here on this project, and it's quite a "tricky move" to think of (as git cloning and checking this `gh-pages` already requires to have git etc).

Maybe you could add, once in a while, this zip file in the release tab and explain that it can be downloaded, saved somewhere for offline use.

Or a simpler action would be to add in the README a link to the zip file: https://github.com/felixhao28/JSCPP/archive/gh-pages.zip

(oh and I also tried to install it using [WebCatalog](https://webcatalog.app/), it works well too!)

**Comment by felixhao28** [comment]
It is tricky to create a pure local webpage with JS/images/CSS files, due to the security limitations of most browsers. I would normally suggest using [http-server](https://www.npmjs.com/package/http-server) as a workaround but WebCatalog seems better.

The `gh-pages`, or the online debugger page, is intended to showcase the capabilities of JSCPP. You can use it if it serves your needs but I don't plan to release it as part of JSCPP.
