### ISSUE TITLE
Goto

### ISSUE THREAD

**Issue by billcollis** [felixhao28/JSCPP#16]
I am looking into using your interpreter to visualise interrupt processing of an embedded system
Having a goto type function that is under external control might make it possible, 
Which parts of your code should I begin to think about to implement this
thanks

**Comment by felixhao28** [comment]
I really really thought very hard on how to interpret gotos. However since the interpreter retains the syntax tree structure and interprets while walking through it, there has to be some kind of complex recursive tree traversal control.

**Comment by billcollis** [comment]
I understand the goto situation which would break the recursion of the tree; (I wrote a C recursive descent parser for C in C#). . What advice would you have about implementing an interrupt type feature, where I could specify a particular node to begin processing and then ultimately return to the same place in the tree? In effect have a manual input to a function call. Thanks so much, 'Bill

**Comment by felixhao28** [comment]
Well, I think my implementation will look like this:

Interpreter will have 3 states: normal, goto forwards and goto backwards.

In the goto forwards state, the interpreter continues while it
1. ignores every single statement
2. goes into a block if target label is inside that block, ignores it otherwise
3. declares variables when no initializer is used, reports error otherwise
4. reset state to normal when target label is met

In the goto backwards state, the interpreter
1. goes to previous single statement of current block
2. goes into a block if target label is inside that block, ignores it otherwise
3. destructs variables when a declaration is found
4. reset state to normal when target label is met

You can speed it up by caching variable scope chain, nodes in call stack at the position of label during the first jump, then you can diff the cached variable scope chain against current variables to decide which variable to construct or destruct for further jumps. Nodes in call stack controls tree traversal. If you already know the syntax tree hierarchy at target label, many search branches can be pruned.
