### ISSUE TITLE
Variable scope

### ISSUE THREAD

**Issue by billcollis** [felixhao28/JSCPP#2]
Hi you have a wonderful piece of code here. Just fantastic,Where do you teach?
Anyway,
I noticed that the scope of debugger.variable() only returns variables within the current scope e.g. in this code
```c++
#include <iostream>
int main() {
    int addtome;
    cin >> addtome;
    for (int index=0; index<3; index++)
     {
        addtome+=index;
     }
     cout<< addme << endl;
    return 0;
}
```
addtome does not show until it has exited the for loop.
I will have a look at  'Debugger.prototype.variable' myself to see if I can change it.
I would like to be able to return a list of the scopes and the vars in each scope as well.

3 years ago I wrote C and BASIC interpreters in C# as part of a visualizer for ATMEL microcontrollers and am now porting it to the web using javascript. I am a newbie with Javascript and was building a peg for C using pegjs and ACE and was looking for information on Generators and Yield and found your code. It's so much better than the recursive parser I wrote in C#! I think I will stop my own port! Now I just need to get my head around nodejs, exports, require, react, coffee, generators....

**Comment by felixhao28** [comment]
Thanks for noticing this project.

I am a teaching assistant for a C programming beginner's course on Coursera. I am considering using this project for the students to do simple exercises like "code completion"/"code correction" in combination of an automatic score giver.

You are totally right about the scope issue. I hesitated to give a list of scopes because there isn't much information on each scope and people may get confused about it. Maybe I will just give a list of all visible variables. There is still much to do with the debugger, such as "step over", "step out" and "immediate window".

The peg files I use are customized to a subset of C++ syntax. If you are going to develop based on the work I have already done, you may want to check on [CONTRIBTUE.md](https://github.com/felixhao28/JSCPP/blob/master/CONTRIBTUE.md). It has some information about how to get started.
