### ISSUE TITLE
empty while loop cause debugger to 

### ISSUE THREAD

**Issue by billcollis** [felixhao28/JSCPP#31]
in the following code if the while loop is empty the debugger goes into a loop and cannot be stopped,
I know its not really a big issue but students writing this in their code while learning will find it hangs their browser, if there is anything in the while loop it wont of course hang up

`#include <iostream>
using namespace std;
int main() {
    int a=0;
    while(1){
        
    }
}`

**Comment by felixhao28** [comment]
I can think of two solutions:

1. Implement a time limit on program execution. This should be pretty easy to do and not that performance impacting. However, a reasonable timeout (like 1 second) is still long enough for user to experience a moment of freeze on the browser, since the JS engine and UI event handling are usually on one thread.
1. Put JSCPP in a web worker. This is slower both in terms of executing and loading, but you will have full control over the JSCPP engine. You can abort the worker anytime you want without causing freeze. I haven't tried this yet so I don't have any example code for you.

If you prefer the previous one, I will see how I can add a time limit. Otherwise I am happy to share your web worker solution in the readme file.

**Comment by billcollis** [comment]
I don't think I would want to slow the execution down at all, and this is for only rare occasions.  So a small freeze time would ok as it would not be that noticeable.
