### ISSUE TITLE
global vars not showing in debugger.variable

### ISSUE THREAD

**Issue by billcollis** [felixhao28/JSCPP#4]
Hi Felix
I noticed today that globals were not being shown by debugger.variable
e.g.

```c++
//vars in scopes
int g=3;
int y=10;
int main()
{
    int x =  2;
    x = func(x);
    x += y;
    return x;
}
int func(int a)
{
    int b =a;
    b = a * a;
    return b;
}
```

Debugging in firefox I realised that in debugger.prototype.variable
the line 
```coffee
for scopeIndex in [@rt.scope.length - 1...0] by -1
```
has three dots so I think it doesn't go down to the global scope '0'

I altered debugger.js 
```js
for (scopeIndex = i = ref = this.rt.scope.length - 1; i > 0; scopeIndex = i += -1) {
```
to
```js
for (scopeIndex = i = ref = this.rt.scope.length - 1; i >= 0; scopeIndex = i += -1) {
```

changing this meant I also had to change the line in the JS 
```js
if (typeof val === "object" && "t" in val && "v" in val)
```
to
```js
if (typeof val === "object" && "t" in val && 'name' in val.t && "v" in val)
```

you do of course have a fuller perspective on my alteration to the code and know its wider effects
cheers
Bill

**Comment by felixhao28** [comment]
Hi Bill,

You are right about the >=0 issue. It has been fixed in the last commit.

However global variables include things like global functions and variables defined in external libraries. Perhaps I will add a "local" tab in the future to suppress showing things like "cin" and "cout".

Thanks,

Felix
