### ISSUE TITLE
Cyrillic text is not supported

### ISSUE THREAD

**Issue by nickkolok** [felixhao28/JSCPP#7]
Greetings from Russia, comrads!

Thanks a lot for your work, it seems to be very useful for partial replacing MS Visual Studio in studying (at least for basics). Unfortunately, our students are useful to make cyrillic annotations for output... which don't work. Here is MWE:

```c++
#include <iostream>

using namespace std;

int main() {
    cout << "some cyrillic text: кириллический текст" <<  endl;
    return 0;
}

```

It seems like I can't send non-ASCII characters to cout:

```c++
#include <iostream>

using namespace std;

int main() {
    cout << "\u0080" <<  endl;
    return 0;
}
```

TypeError: Cannot read property 'type' of undefined

Of course, this limitaion could be easily worked around with a kostyl like punycode, but it seems to be very unpleasant.

Text below is in Russian

Доброго времени суток, товарищи!

Текст выше - на английском. Спасибо за проделанную работу, либа годная, частично может заменить проклятую проприетарную MS Visual Studio для совсем уж первокурсников (хотя бы на время, пока они её крякают). И вообще, да здравствует импортозамещение!

Однако, незадача: кириллический текст запихнуть в cout не получается. Да вообще ничего, кроме ASCII, не получается. Примеры выше. Нет, конечно, мы, суровые русские программисты, ко всяким санкциям привычны, костылей-то напаяем (хоть punycode), но всё равно неприятно.

**Comment by felixhao28** [comment]
Show be fixed here: 2ba7baac7f70d6526eba5c79484887fd82848a80. However I am not sure if my fix conflicts with C++ standard since without [explicit prefix](http://en.cppreference.com/w/cpp/language/string_literal), I try to [use wchar_t instead of char](https://github.com/felixhao28/JSCPP/commit/2ba7baac7f70d6526eba5c79484887fd82848a80#diff-ae38a11a829764f7ca0d93c0e9318f7dR660).
